/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.flysafairreservation;

import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTextField;
/**
 *
 * @author wahin
 */
public class AvalibilityForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvalibilityForm.class.getName());
    private String departure, arrival;
    private String passengerName, email;

    private JTextField departureTF, arrivalTF;
    /**
     * Creates new form AvalibilityForm
     */
    public AvalibilityForm(String departure, String arrival, String passengerName, String email) {
        this.passengerName = passengerName;
        this.departure = departure;
        this.arrival = arrival;
        this.email = email;
        
        initComponents();

    // 🔹 Set flight options
    flightComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
        "Flight204", "Flight3000", "Flight78", "Flight64"
    }));

    // 🔹 Set seat options
    seatComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
        "1A", "1B", "1C", "2A", "2B", "2C",
        "3A", "3B", "3C", "4A", "4B", "4C",
        "5A", "5B", "5C", "6A", "6B", "6C"
    }));

    // 🔹 Define available seats
    List<String> availableSeats = Arrays.asList(
        "5A", "1B", "4C", "2A", "2B", "2C",
        "3A", "4B", "3C"
    );

    // 🔹 Flight selection updates price, departure time, and arrival time
    flightComboBox.addActionListener(e -> {
        String selectedFlight = (String) flightComboBox.getSelectedItem();
        String price = "";
        String departureTime = "";
        String arrivalTime = "";

        switch (selectedFlight) {
            case "Flight204":
                price = "R1200";
                departureTime = "08h15AM";
                arrivalTime = "11h30AM";
                break;
            case "Flight3000":
                price = "R1800";
                departureTime = "10h00AM";
                arrivalTime = "12h30AM";
                break;
            case "Flight78":
                JOptionPane.showMessageDialog(null, "Flight78 is currently delayed.");
                price = "R950";
                departureTime = "16h30PM";
                arrivalTime = "18h30PM";
                break;
            case "Flight64":
                JOptionPane.showMessageDialog(null, "Flight64 has been canceled.");
                price = "R1500";
                departureTime = "20h00PM";
                arrivalTime = "22h00PM";
                break;
        }

        priceComboBox.setModel(new DefaultComboBoxModel<>(new String[] { price }));
        departureComboBox.setModel(new DefaultComboBoxModel<>(new String[] { departureTime }));
        arrivalComboBox.setModel(new DefaultComboBoxModel<>(new String[] { arrivalTime }));
    });

    // 🔹 Seat selection checks availability
    seatComboBox.addActionListener(e -> {
        String selectedSeat = (String) seatComboBox.getSelectedItem();
        if (!availableSeats.contains(selectedSeat)) {
            JOptionPane.showMessageDialog(null, "Seat occupied");
        }
    });

    // 🔹 Trigger initial flight selection to show price/time on launch
    flightComboBox.setSelectedIndex(0);

    // 🔹 Set passed-in departure and arrival cities

    setLocationRelativeTo(null); // Center the window
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        continueBtn = new javax.swing.JButton();
        flightComboBox = new javax.swing.JComboBox<>();
        seatComboBox = new javax.swing.JComboBox<>();
        arrivalComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        departureComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priceComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        continueBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        continueBtn.setText("Continue");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        jPanel1.add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 66, 142, -1));

        flightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(flightComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(seatComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        arrivalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(arrivalComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 500, 130));

        jPanel2.setBackground(new java.awt.Color(255, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlySafair-brand-logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 77));

        departureComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(departureComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Flight No");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 72, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Departure Time");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Price");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 38, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Seat No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 151, -1, -1));

        priceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(priceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Arrival Time");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed

    // 🔹 Get selected flight and seat
    String flight = (String) flightComboBox.getSelectedItem();
    String seat = (String) seatComboBox.getSelectedItem();

    // 🔹 Validation checks
    boolean isFlightCanceled = flight.equals("Flight64");
    boolean isFlightDelayed = flight.equals("FlightMzansi");
    boolean isSeatTaken = !Arrays.asList(
        "5A", "1B", "4C", "2A", "2B", "2C", "3A", "4B", "3C"
    ).contains(seat);

    // 🔹 Block if flight is canceled or seat is taken
    if (isFlightCanceled || isSeatTaken) {
        String message = "⚠️ Selected fields are unavailable:\n";
        if (isFlightCanceled) message += "- " + flight + " is canceled.\n";
        if (isSeatTaken) message += "- Seat " + seat + " is occupied.\n";
        message += "Please choose a new flight and seat.";
        JOptionPane.showMessageDialog(null, message, "Selection Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 🔹 Warn if flight is delayed
    if (isFlightDelayed) {
        JOptionPane.showMessageDialog(null,
            "⏳ " + flight + " is currently delayed.\nYou may proceed, but expect changes.",
            "Flight Delayed", JOptionPane.WARNING_MESSAGE);
    }

    // 🔹 Get remaining flight details
    String departureTime = (String) departureComboBox.getSelectedItem();
    String arrivalTime = (String) arrivalComboBox.getSelectedItem();

    // 🔹 Use stored departure/arrival from constructor
    // These were passed from FlightDetailsForm
    // and stored in class-level variables: departure, arrival

    // 🔹 Launch TicketForm with all data
    TicketForm ticket = new TicketForm(
        flight, seat,
        departure, arrival, departureTime, arrivalTime, passengerName, email

    );
    ticket.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_continueBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arrivalComboBox;
    private javax.swing.JButton continueBtn;
    private javax.swing.JComboBox<String> departureComboBox;
    private javax.swing.JComboBox<String> flightComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> priceComboBox;
    private javax.swing.JComboBox<String> seatComboBox;
    // End of variables declaration//GEN-END:variables
}
