/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.flysafairreservation;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author wahin
 */
public class FlightDetailsForm extends javax.swing.JFrame {
    
    private String flightType;
    private String passengerName;
  
    public FlightDetailsForm(String flightType, String passengerName) {
        this.flightType = flightType;
        this.passengerName = passengerName;
        initComponents();
        flightTypeLabel.setText("Flight Type: " + flightType);
        if (flightType.equals("Domestic")) {
            sourceComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
                "Cape Town", "Johannesburg", "Durban"
        }));
            destinationComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
                "Port Elizabeth", "Bloemfontein", "East London"
            }));
        } else {
            sourceComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
                "Cape Town International", "OR Tambo International"
            }));
            destinationComboBox.setModel(new DefaultComboBoxModel<>(new String[] {
                "London Heathrow", "Dubai", "New York JFK"
            }));
        }

        setLocationRelativeTo(null); // center the form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sourceComboBox = new javax.swing.JComboBox<>();
        destinationComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        flightTypeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Flight Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 138, 20));

        sourceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(sourceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        destinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(destinationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));

        flightTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(flightTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlySafair-brand-logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 72));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Source");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 190));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedDeparture = (String) sourceComboBox.getSelectedItem();
        String selectedArrival = (String) destinationComboBox.getSelectedItem();
        AvalibilityForm availability = new AvalibilityForm(selectedDeparture, selectedArrival, passengerName);
        availability.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> destinationComboBox;
    private javax.swing.JLabel flightTypeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> sourceComboBox;
    // End of variables declaration//GEN-END:variables
}
