/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.flysafairreservation;
import javax.swing.JOptionPane;
/**
 *
 * @author wahin
 */
public class FlightTypeForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightTypeForm.class.getName());
    private final String passengerName;
    private final String email;
    public FlightTypeForm(String passengerName, String email) {
        this.passengerName = passengerName;
        this.email = email;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        domesticBtn = new javax.swing.JRadioButton();
        interBtn = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlySafair-brand-logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 91));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Select Flight Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        buttonGroup1.add(domesticBtn);
        domesticBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        domesticBtn.setText("Domestic");
        getContentPane().add(domesticBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        buttonGroup1.add(interBtn);
        interBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        interBtn.setText("International");
        getContentPane().add(interBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedType;
        if (domesticBtn.isSelected()) {
            selectedType = "Domestic";
        } else if (interBtn.isSelected()) {
            selectedType = "International";
        }else {
            JOptionPane.showMessageDialog(this, "Please select a flight type.");
            return;
        }  
        FlightDetailsForm detailsForm = new FlightDetailsForm(selectedType,passengerName, email);
        detailsForm.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton domesticBtn;
    private javax.swing.JRadioButton interBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
