/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.flysafairreservation;

/**
 *
 * @author wahin
 */
public class TicketForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketForm.class.getName());

    /**
     * Creates new form TicketForm
     */
    public TicketForm(String flight, String seat, String departure, String arrival, String departureTime, String arrivalTime, String passengerName) {
        initComponents();
        flightNoTF.setText(flight);
        seatNoTF.setText(seat);
        departureTF.setText(departure);
        arrivalTF.setText(arrival);
        departureTimeTF.setText(departureTime);
        arrivalTimeTF.setText(arrivalTime);
        passengerNameTF.setText(passengerName);
        departureTF.setEditable(false);
        arrivalTF.setEditable(false);
        passengerNameTF.setEditable(false);
        flightNoTF.setEditable(false);
        seatNoTF.setEditable(false);
        departureTimeTF.setEditable(false);
        arrivalTimeTF.setEditable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FligthIconTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        seatNoTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        arrivalTF = new javax.swing.JTextField();
        arrivalTimeTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        flightNoTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departureTF = new javax.swing.JTextField();
        departureTimeTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        passengerNameTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Boarding Pass");

        FligthIconTF.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(seatNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Seat No");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 50, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seat 24.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 30, 20));
        jPanel2.add(arrivalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, -1));
        jPanel2.add(arrivalTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Arrival");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FlySafair-brand-logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 200, 60));
        jPanel2.add(flightNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Your Flight");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane (4).png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Depature");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel2.add(departureTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));
        jPanel2.add(departureTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/120 pdf417.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Boarding pass");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setText("HVo8SW");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, -1));
        jPanel2.add(passengerNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Passenger Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Check-in and baggage check-in close 40 minutes prior to depature");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 380, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FligthIconTF;
    private javax.swing.JTextField arrivalTF;
    private javax.swing.JTextField arrivalTimeTF;
    private javax.swing.JTextField departureTF;
    private javax.swing.JTextField departureTimeTF;
    private javax.swing.JTextField flightNoTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField passengerNameTF;
    private javax.swing.JTextField seatNoTF;
    // End of variables declaration//GEN-END:variables
}
